---
- name: nas-server playbook
  hosts: nas
  roles:
    - ../../roles/common
    - ../../roles/docker-node
    - ../../roles/zfs

  tasks:
    - name: nfs-server
      include: nfs-server.yaml
    - name: samba-server
      include: samba-server.yaml
