# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  config.vm.provider "virtualbox"

  config.vm.synced_folder './', '/vagrant', type: "rsync", rsync__args: ["--verbose","--recursive","-K","--copy-links"], disabled: false

  config.vm.box = "debian/bullseye64"
  cpus = 8
  memory = 4098

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = cpus
    vb.memory = memory
    vb.gui = true
  end

  # Use system network bridge interface
  bridge_host_interface_name = "Realtek PCIe 2.5GbE Family Controller"
  config.vm.network "public_network", bridge: bridge_host_interface_name, ip: "10.0.0.74"

  # nas
  config.vm.define "nas" do |nas|
    nas.vm.hostname = "bigusdiskus"

    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "nas-server.yaml"
    end

  end

end
