---
- hosts: all
  roles:
    - ../roles/common
    - ../roles/docker-node
      # - ../roles/zfs

  tasks:
    - name: Install nfs kernal
      become: true
      package:
        state: present
        name:
          - nfs-common
          - nfs-kernel-server
          - portmap
