---
- name: nas-server playbook
  hosts: all
  roles:
    - ../roles/common
    - ../roles/docker-node
      # - ../roles/zfs

  vars:
    rw_hosts:
      - host1.example.com

  tasks:
    - name: nfs-server
      include: nfs-server.yaml
