---
- name: Install supporting packages
  become: true
  apt:
    state: present
    name:
      - git
      - ca-certificates
      - curl
      - gnupg
      - lxc
      - apparmor-utils

- name: Add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository  # TODO: add based on arch
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker Engine
  become: true
  apt:
    name:
      - python3-requests
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: add_to_docker_group_result

- name: Reset ssh connection to allow group add to take effect so we don't need to run ansible twice
  ansible.builtin.meta:
    reset_connection
  when: add_to_docker_group_result.changed == true

- name: Start Docker service
  become: true
  service:
    name: docker
    state: started

- name: docker apparmor file
  become: true
  copy:
    dest: "/root/nfs-apparmor.txt"
    content: |
      #include <tunables/global>
      profile docker-nfs flags=(attach_disconnected,mediate_deleted) {
        #include <abstractions/lxc/container-base>
        mount fstype=nfs*,
        mount fstype=rpc_pipefs,
      }

- name: docker apparmor
  become: true
  command:
    argv:
      - /usr/sbin/apparmor_parser
      - -r
      - -W
      - /root/nfs-apparmor.txt
