---
- name: Install supporting packages
  become: true
  apt:
    state: present
    name:
      - git
      - ca-certificates
      - curl
      - gnupg

- name: Add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install Docker Engine
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker

- name: Start Docker service
  become: true
  service:
    name: docker
    state: started
