---

# Install packages per OS
- include: debian.yaml
  when: ansible_os_family == "Debian"


# Setup the shared networks
- name: Docker networks
  become: yes
  docker_network:
      name: "{{item}}"
  loop:
      - traefik-network
      - docker-socket-network

# Pull down and launch the common services
- name: Pull down docker compose files
  git:
      repo: https://github.com/PastaMasta/docker-composies.git
      dest: ./docker-composies
      clone: true
      update: true
      depth: 1

# Start treafik, docker proxy and portainer agent?
- name: Launch common-services
  community.docker.docker_compose_v2:
      project_src: ./docker-composies/common-services
  register: output

- name: show results
  debug:
    var: output
