---
- include: debian.yaml
  when: ansible_os_family == "Debian"

- name: Docker networks
  docker_network:
      name: "{{item}}"
  loop:
      - traefik-network
      - docker-socket-network

- name: Pull down docker compose files
  git:
    repo: https://github.com/PastaMasta/docker-composies.git
    dest: ./docker-composies
    clone: true
    update: true
    depth: 1

# Start treafik, docker proxy and portainer agent?
